version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_PORT}"
    expose:
      - ${DATABASE_PORT}
    networks:
      - internalnet
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 0s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "${BACKEND_HOST_PORT}:3000"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    environment:
      DATABASE_HOST: ${DATABASE_HOST} # Use the service name as the host
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      -  internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  dev-db-data:
  prod-db-data:
