version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE:HOST: ${DATABASE_HOST}
      MYSQL_DATABASE_PORT: ${DATABASE_PORT}
      MYSQL_DATABASE_NAME: ${DATABASE_NAME}
      MYSQL_USER:          ${DATABASE_USER}
      MYSQL_PASSWORD:      ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_NAME=${DATABASE_NAME}e
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mysql

volumes:
  db_data:
