const constants = {
  internalServerError: 'Internal server error',
  invalidCredentialsError: 'Invalid credentials',
  inputFieldError: 'Input field error',
  emailAlreadyExistsError: 'Email already exists',
  emailFormatInvalidError: 'Email format invalid',
  weakPasswordError: 'Password is not strong enough',
  accountNotFoundError: 'Account not found',
  accountRegistrationSuccess: 'Account registered successfully',
  deviceNotFoundError: 'Device not found',
  clientNotFoundError: 'Client not found',
  zoneNotFoundError: 'Zone not found',
  partitionNotFoundError: 'Partition not found',
  duplicateFoundError: 'Duplicate entry found',
  deviceDeletionSuccess: 'Device deleted successfully',
  zoneDeletionSuccess: 'Zone deleted successfully',
  clientDeletionSuccess: 'Client deleted successfully',
  partitionDeletionSuccess: 'Partition deleted successfully',
  noZoneFound: 'No zone found',
  noClientFound: 'No client found',
  noDeviceFound: 'No device found',
  noPartitionFound: 'No partition found',
};

export default constants;