export const eventIdByName = {
  'Medical': '1100',
  'Personal Emergency': '1101',
  'Fail to Report In': '1102',
  'Fall Detected': '1103',
  'Fire': '1110',
  'Smoke': '1111',
  'Combustion': '1112',
  'Water Flow': '1113',
  'Heat': '1114',
  'Pull Station': '1115',
  'Duct': '1116',
  'Flame': '1117',
  'Near Alarm': '1118',
  'Panic': '1120',
  'Ambush': '1121',
  'Silent': '1122',
  'Audible': '1123',
  'Duress - Access Granted': '1124',
  'Duress - Egress Granted': '1125',
  'Hold-up Suspicion Print': '1126',
  'Panic Verifier': '1129',
  'Burglary': '1130',
  'Perimeter': '1131',
  'Interior': '1132',
  '24 Hour (Safe)': '1133',
  'Intrare': '1134',
  'Day': '1135',
  'Outdoor': '1136',
  'Tamper': '1137',
  'Near AlARM': '1138',
  'Intrusion verifier': '1139',
  'General Alarm': '1140',
  'Polling Loop Open': '1331',
  'Polling Loop Short': '1332',
  'Expansion Module Failure': '1333',
  'Sensor Tamper': '1383',
  'Keypad Tamper Open': '1145',
  'Silent Burglary': '1146',
  'Sensor Supervision Failure': '1147',
  '24 Hour Non-Burglary': '1150',
  'Gas Detected': '1151',
  'Refrigeration': '1152',
  'Loss Of Heat': '1153',
  'Water Leakage': '1154',
  'Foil Break': '1155',
  'Day Trouble': '1156',
  'Low Bottled Gas Level': '1157',
  'High Temp': '1158',
  'Low Temp': '1159',
  'Loss Of Air Flow': '1161',
  'Carbon Monoxide Detected': '1162',
  'Tank Level': '1163',
  'High Humidity': '1168',
  'Low Humidity': '1169',
  'Fire Supervisory': '1200',
  'Low Water Pressure': '1201',
  'Low CO2': '1202',
  'Gate Valve Sensor': '1203',
  'Low Water Level': '1204',
  'Pump Activated': '1205',
  'Pump Failure': '1206',
  'AUX Overload': '1300',
  'AC Loss': '1301',
  'Low System Battery': '1302',
  'RAM Checksum Bad': '1303',
  'ROM Checksum Bad': '1304',
  'System Reset': '1305',
  'Panel Programming Changed': '1306',
  'Self-Test Failure': '1307',
  'System Shutdown': '1308',
  'Battery Test Failure': '1309',
  'Ground Fault': '1310',
  'Battery Missing/Dead': '1311',
  'Power Supply Overcurrent': '1312',
  'Engineer Reset': '1313',
  'Primary Power Supply Failure': '1314',
  'System Trouble': '1315',
  'System Tampe': '1316',
  'Control Panel System Tamper': '1317',
  'Sounder/Relay': '1320',
  'Bell 1 Trouble': '1321',
  'Bell 2 Trouble': '1322',
  'Alarm Relay': '1323',
  'Trouble Relay': '1324',
  'Reversing Relay': '1325',
  'Notification Appliance Ckt. # 3': '1326',
  'Notification Appliance Ckt. # 4': '1327',
  'System Peripheral Trouble': '1330',
  'Repeater Failure': '1334',
  'Local Printer Out Of Paper': '1335',
  'Local Printer Failure': '1336',
  'Exp. Module DC Loss': '1337',
  'Exp. Module Low Batt.': '1338',
  'Exp. Module Reset': '1339',
  'Exp. Module Tamper': '1341',
  'Exp. Module AC Loss': '1342',
  'Exp. Module Self-Test Fail': '1343',
  'RF Receiver Jam Detect': '1344',
  'AES Encryption Disabled': '1345',
  'Communication Trouble': '1350',
  'Telco 1 Fault': '1351',
  'Telco 2 Fault': '1352',
  'Long Range Radio Xmitter Fault': '1353',
  'Failure To Communicate Event': '1354',
  'Loss Of Radio Supervision': '1355',
  'Loss Of Central Polling': '1356',
  'Long Range Radio VSWR Problem': '1357',
  'Periodic Comm Test Fail': '1358',
  'Protection Loop': '1370',
  'Protection Loop Open': '1371',
  'Protection Loop Short': '1372',
  'Fire Trouble': '1373',
  'Exit Error Alarm (Zone)': '1374',
  'Panic Zone Trouble': '1375',
  'Hold-Up Zone Trouble': '1376',
  'Swinger Trouble': '1377',
  'Cross-zone Trouble': '1378',
  'Sensor Trouble': '1380',
  'Loss of RF Supervision': '1381',
  'Loss Of Supervision - RPM': '1382',
  'RF Low Battery': '1384',
  'Smoke Detector Hi Sensitivity': '1385',
  'Smoke Detector Low Sensitivity': '1386',
  'Intrusion Detector Hi Sensitivity': '1387',
  'Intrusion Detector Low Sensitivity': '1388',
  'Sensor Self-Test Failure': '1389',
  'Sensor Watch Trouble': '1391',
  'Drift Compensation Error': '1392',
  'Maintenance Alert': '1393',
  'CO Detector Needs Replacement': '1394',
  'Open': '1400',
  'Disarming by user': '1401',
  'Group of zones disarmed': '1402',
  'Timed Autodisarming': '1403',
  'Late Disarming': '1404',
  'Cancel Autoarming': '1405',
  'Cancel': '1406',
  'Remote Disarm': '1407',
  'Quick arming': '1408',
  'Keyswitch Disarming': '1409',
  'Callback Request Made': '1411',
  'PC Connected': '1412',
  'Unsuccessful Access': '1413',
  'System Shutdown Command Received': '1414',
  'Dialer Shutdown Command Received': '1415',
  'Successful Upload': '1416',
  'Keypad Lockout': '1421',
  'PGM Activated by User': '1422',
  'Guard Round Ambush': '1423',
  'Egress Denied': '1424',
  'Egress Granted': '1425',
  'Access Door Propped Open': '1426',
  'Access Point Door Status Monitor Trouble': '1427',
  'Access Point Request To Exit Trouble': '1428',
  'Guard Round Starts': '1429',
  'Guard Round Finish': '1430',
  'Access Threat Level Change': '1431',
  'Access Relay/Trigger Fail': '1432',
  'Access RTE Shunt': '1433',
  'Access DSM Shunt': '1434',
  'Second Person Access': '1435',
  'Irregular Access': '1436',
  'Armed with System Trouble Override': '1443',
  'Exception Open': '1450',
  'Early Open': '1451',
  'Late Open': '1452',
  'Failed To Open': '1453',
  'Failed To Close': '1454',
  'Autoarm Failed': '1455',
  'Exit Error (User)': '1457',
  'User On Premises': '1458',
  'Recent Close': '1459',
  'Wrong Code Entry': '1461',
  'Legal Code Entry': '1462',
  'Re-Arm After Alarm': '1463',
  'auto-Arm Time Extended': '1464',
  'Panic Alarm Reset': '1465',
  'Service On Premises': '1466',
  'Access Reader Disable': '1501',
  'Sounder/Relay Disable': '1520',
  'Bell 1 Disable': '1521',
  'Bell 2 Disable': '1522',
  'Alarm Relay Disable': '1523',
  'Trouble Relay Disable': '1524',
  'Reversing Relay Disable': '1525',
  'Notification Appliance Ckt. # 3 Disable': '1526',
  'Notification Appliance Ckt. # 4 Disable': '1527',
  'Module Added': '1531',
  'Module Removed': '1532',
  'Dialer Disabled': '1551',
  'Radio Transmitter Disabled': '1552',
  'Remote Upload/Download Disabled': '1553',
  'Fiber Converter Fault': '1554',
  'Fiber Network Fault': '1555',
  'Zone Bypass': '1570',
  'Fire Bypass': '1571',
  '24 Hour Zone Bypass': '1572',
  'Burg. Bypass': '1573',
  'Group Bypass': '1574',
  'Swinger Bypass': '1575',
  'Access Zone Shunt': '1576',
  'Access Point Bypass': '1577',
  'Vault Bypass': '1578',
  'Vent Zone Bypass': '1579',
  'Manual Trigger Test Report': '1601',
  'Periodic Test Report': '1602',
  'Periodic RF Transmission': '1603',
  'Fire Test': '1604',
  'Status Report To Follow': '1605',
  'Listen-In To Follow': '1606',
  'Walk Test Mode': '1607',
  'Periodic Test - System Trouble Present': '1608',
  'Video Xmitter Active': '1609',
  'Round OK': '1611',
  'Round Failed': '1612',
  'Intrusion Zone Walk Tested': '1613',
  'Fire Zone Walk Tested': '1614',
  'Panic Zone Walk Tested': '1615',
  'Service Request': '1616',
  'Event Log Reset': '1621',
  'Event Log 50% Full': '1622',
  'Event Log 90% Full': '1623',
  'Event Log Overflow': '1624',
  'Time/Date Reset': '1625',
  'Time/Date Inaccurate': '1626',
  'Program Mode Entry': '1627',
  'Program Mode Exit': '1628',
  '32 Hour Event Log Marker': '1629',
  'Schedule Change': '1630',
  'Exception Schedule Change': '1631',
  'Access Schedule Change': '1632',
  'Senior Watch Trouble': '1641',
  'Latch-Key Supervision': '1642',
  'Restricted Door Opened': '1643',
  'Help Arrived': '1645',
  'Additional Help Needed': '1646',
  'Additional Help Cancel': '1647',
  'Reserved For Ademco Use': '1653',
  'System Inactivity': '1654',
  'User Code X modified by Installer': '1655',
  'Auxiliary #3': '1703',
  'Installer Test': '1704',
  'LINE is Free': '1760',
  'INPUT 1 is ON': '1761',
  'INPUT 2 is ON': '1762',
  'PGM 1 is ON': '1763',
  'PGM 2 is ON': '1764',
  'PGM 3 is ON': '1765',
  'PGM 4 is ON': '1766',
  'INPUT 3 is ON': '1767',
  'GPRS Initialization Failure': '1770',
  'Ethernet Failure': '1771',
  'GPRS Failure': '1772',
  'Low Cellular Signal': '1774',
  'Cellular Module Removed': '1775',
  'SIM Card Removed': '1776',
  'Input Bypassed': '1777',
  'Unable to output signal (Derived Channel)': '1796',
  'STU Controller down (Derived Channel)': '1798',
  'Auto-close with Bypass': '1910',
  'Bypass Closing': '1911',
  'Fire Alarm Silence': '1912',
  'Supervisory Point test Start/End': '1913',
  'Hold-up test Start/End': '1914',
  'Burg. Test Print Start/End': '1915',
  'Supervisory Test Print Start/End': '1916',
  'Burg. Diagnostics Start/End': '1917',
  'Fire Diagnostics Start/End': '1918',
  'Untyped diagnostics': '1919',
  'Trouble Closing (Closed with burg. during exit)': '1920',
  'Access Denied Code Unknown': '1921',
  'Supervisory Point Alarm': '1922',
  'Supervisory Point Bypass': '1923',
  'Supervisory Point Trouble': '1924',
  'Hold-up Point Bypass': '1925',
  'AC Failure for 4 hours': '1926',
  'Output Trouble': '1927',
  'User code for event': '1928',
  'Log-off': '1929',
  'CS Connection Failure': '1954',
  'Rcvr Database Connection Fail/Restore': '1961',
  'License Expiration Notification': '1962',
  'Medical Alarm Restore': '3100',
  'Personal Emergency Restore': '3101',
  'Communication Error Restore': '3102',
  'Fire Restore': '3110',
  'Smoke Restore': '3111',
  'Combustion Restore': '3112',
  'Water Flow Restore': '3113',
  'Heat Restore': '3114',
  'Pull Station Restore': '3115',
  'Duct Restore': '3116',
  'Flame Restore': '3117',
  'Near Alarm Restore': '3138',
  'Panic Restore': '3120',
  'Ambush Restore': '3121',
  'Silent Restore': '3122',
  'Audible Restore': '3123',
  'Duress \u00e2\u20ac\u201c Access Granted Restore': '3124',
  'Duress \u00e2\u20ac\u201c Egress Granted Restore': '3125',
  'Burglary Restore': '3130',
  'Perimeter Restore': '3131',
  'Interior Restore': '3132',
  '24 Hour (Safe) Restore': '3133',
  'Exit': '3134',
  'Night': '3135',
  'Outdoor Restore': '3136',
  'Tamper Restore': '3137',
  'Intrusion Verifier Restore': '3139',
  'General Alarm Restore': '3140',
  'Polling Loop Open Restore': '3331',
  'Polling Loop Short Restore': '3332',
  'Expansion Module Failure Restore': '3333',
  'Tamper Senzor Restore': '3144',
  'Extension Module Tamper Restore': '3145',
  'Silent Burglary Restore': '3146',
  'Sensor Supervision Failure Restore': '3147',
  '24 Hour Non-Burglary Restore': '3150',
  'Gas Detected Restore': '3151',
  'Refrigeration Restore': '3152',
  'Loss Of Heat Restore': '3153',
  'Water Leakage Restore': '3154',
  'Foil Break Restore': '3155',
  'Day Trouble Restore': '3156',
  'Low Bottled Gas Level Restore': '3157',
  'High Temp Restore': '3158',
  'Low Temp Restore': '3159',
  'Loss Of Air Flow Restore': '3161',
  'Carbon Monoxide Detected Restore': '3162',
  'Tank Level Restore': '3163',
  'Fire Supervisory Restore': '3200',
  'Low Water Pressure Restore': '3201',
  'Low CO2 Restore': '3202',
  'Gate Valve Sensor Restore': '3203',
  'Low Water Level Restore': '3204',
  'Pump Activated Restore': '3205',
  'Pump Failure Restore': '3206',
  'AUX Overload Restore': '3300',
  'AC Restore': '3301',
  'System Battery Restore': '3302',
  'RAM Checksum Restore': '3303',
  'ROM Checksum Restore': '3304',
  'System Reset Restore': '3305',
  'Panel Programming Changed Restore': '3306',
  'Self-Test Failure Restore': '3307',
  'System Shutdown Restore': '3308',
  'Battery Test Failure Restore': '3309',
  'Ground Fault Restore': '3310',
  'Battery Missing/Dead Restore': '3311',
  'Power Supply Overcurrent Restore': '3312',
  'Engineer Reset Restore': '3313',
  'Sounder/Relay Restore': '3320',
  'Bell 1 Trouble Restore': '3321',
  'Bell 2 Trouble Restore': '3322',
  'Alarm Relay Restore': '3323',
  'Trouble Relay Restore': '3324',
  'Reversing Relay Restore': '3325',
  'Notification Appliance Ckt. # 3 Restore': '3326',
  'Notification Appliance Ckt. # 4 Restore': '3327',
  'System Peripheral Trouble  Restore': '3330',
  'Repeater Failure Restore': '3334',
  'Local Printer Out Of Paper Restore': '3335',
  'Local Printer Failure Restore': '3336',
  'Exp. Module DC Loss Restore': '3337',
  'Exp. Module Low Batt. Restore': '3338',
  'Exp. Module Reset Restore': '3339',
  'Exp. Module Tamper Restore': '3341',
  'Exp. Module AC Loss Restore': '3342',
  'Exp. Module Self-Test Fail Restore': '3343',
  'RF Receiver Jam Detect Restore': '3344',
  'AES Encryption Enabled': '3345',
  'Communication Trouble Restore': '3350',
  'Telco 1 Fault Restore': '3351',
  'Telco 2 Fault Restore': '3352',
  'Long Range Radio Xmitter Fault Restore': '3353',
  'Failure To Communicate Event Restore': '3354',
  'Loss Of Radio Supervision Restore': '3355',
  'Loss Of Central Polling Restore': '3356',
  'Long Range Radio VSWR Problem Restore': '3357',
  'Periodic Comm Test Restore': '3358',
  'Protection Loop Restore': '3370',
  'Protection Loop Open Restore': '3371',
  'Protection Loop Short Restore': '3372',
  'Fire Trouble Restore': '3373',
  'Exit Error Alarm (Zone) Restore': '3374',
  'Panic Zone Trouble Restore': '3375',
  'Hold-Up Zone Trouble Restore': '3376',
  'Swinger Trouble Restore': '3377',
  'Cross-zone Trouble Restore': '3378',
  'Sensor Trouble Restore': '3380',
  'RF Supervision Restore': '3381',
  'Loss Of Supervision - RPM Restore': '3382',
  'Sensor Tamper Restore': '3383',
  'RF Battery Restore': '3384',
  'Smoke Detector Hi Sensitivity Restore': '3385',
  'Smoke Detector Low Sensitivity Restore': '3386',
  'Intrusion Detector Hi Sensitivity Restore': '3387',
  'Intrusion Detector Low Sensitivity Restore': '3388',
  'Sensor Self-Test Failure Restore': '3389',
  'Sensor Watch Trouble Restore': '3391',
  'Drift Compensation Error Restore': '3392',
  'Maintenance Alert Restore': '3393',
  'Close': '3400',
  'Arming by user': '3401',
  'Group of zones armed': '3402',
  'Timed Autoarming': '3403',
  'Inactivity Autoarming': '3404',
  'Remote Arm': '3407',
  'Quick STAY Arm': '3408',
  'Keyswitch Arming': '3409',
  'PC Disconnected': '3412',
  'PGM Deactivated by User': '3422',
  'Access Door Propped Open Restore': '3426',
  'Access Point Door Status Monitor Trouble Restore': '3427',
  'Access Point Request To Exit Trouble Restore': '3428',
  'Access Relay/Trigger Fail Restore': '3432',
  'Access RTE Shunt Restore': '3433',
  'Access DSM Shunt Restore': '3434',
  'Armed STAY': '3441',
  'Keyswitch Armed Stay': '3442',
  'Exception Close': '3450',
  'Early Close': '3451',
  'Late Close': '3452',
  'Partial Arm': '3456',
  'Service Off Premises': '3466',
  'Access Reader Enable': '3501',
  'Sounder/Relay Enable': '3520',
  'Bell 1 Enable': '3521',
  'Bell 2 Enable': '3522',
  'Alarm Relay Enable': '3523',
  'Trouble Relay Enable': '3524',
  'Reversing Relay Enable': '3525',
  'Dialer Enabled': '3551',
  'Radio Transmitter Enabled': '3552',
  'Remote Upload/Download Enabled': '3553',
  'Zone Bypass Cancel': '3570',
  'Fire Bypass Cancel': '3571',
  '24 Hour Zone Bypass Cancel': '3572',
  'Burg. Bypass Cancel': '3573',
  'Group Bypass Cancel': '3574',
  'Swinger Bypass Cancel': '3575',
  'Access Zone Shunt Open': '3576',
  'Access Point Bypass Cancel': '3577',
  'Time/Date Restore': '3626',
  'LINE is Restored': '3760',
  'INPUT 1 is OFF': '3761',
  'INPUT 2 is OFF': '3762',
  'PGM 1 is OFF': '3763',
  'PGM 2 is OFF': '3764',
  'PGM 3 is OFF': '3765',
  'PGM 4 is OFF': '3766',
  'INPUT 3 is OFF': '3767',
  'GPRS Initialization OK': '3770',
  'Ethernet is UP': '3771',
  'GPRS is UP': '3772',
  'Normal Cellular Signal': '3774',
  'Cellular Module Inserted': '3775',
  'SIM Card Inserted': '3776',
  'Input Restored': '3777'
};

// Define the new EventInfo class
export class EventInfo {
  constructor(name, type, color) {
    this.name = name;
    this.type = type;
    this.color = color;
  }
}

export const eventMapById = {
  '1100': new EventInfo('Medical', 'Zone', 'red'),
  '1101': new EventInfo('Personal Emergency', 'Zone', 'red'),
  '1102': new EventInfo('Fail to Report In', 'Zone', 'red'),
  '1103': new EventInfo('Fall Detected', 'Zone', 'red'),
  '1110': new EventInfo('Fire', 'Zone', 'red'),
  '1111': new EventInfo('Smoke', 'Zone', 'red'),
  '1112': new EventInfo('Combustion', 'Zone', 'red'),
  '1113': new EventInfo('Water Flow', 'Zone', 'red'),
  '1114': new EventInfo('Heat', 'Zone', 'red'),
  '1115': new EventInfo('Pull Station', 'Zone', 'red'),
  '1116': new EventInfo('Duct', 'Zone', 'red'),
  '1117': new EventInfo('Flame', 'Zone', 'red'),
  '1118': new EventInfo('Near Alarm', 'Zone', 'red'),
  '1120': new EventInfo('Panic', 'Zone', 'red'),
  '1121': new EventInfo('Ambush', 'User', 'red'),
  '1122': new EventInfo('Silent', 'Zone', 'red'),
  '1123': new EventInfo('Audible', 'Zone', 'red'),
  '1124': new EventInfo('Duress - Access Granted', 'Zone', 'red'),
  '1125': new EventInfo('Duress - Egress Granted', 'Zone', 'red'),
  '1126': new EventInfo('Hold-up Suspicion Print', 'User', 'red'),
  '1129': new EventInfo('Panic Verifier', 'Zone', 'red'),
  '1130': new EventInfo('Burglary', 'Zone', 'red'),
  '3130': new EventInfo('Burglary Restore', 'Zone', 'green'),
  '1131': new EventInfo('Perimeter', 'Zone', 'red'),
  '1132': new EventInfo('Interior', 'Zone', 'red'),
  '1133': new EventInfo('24 Hour (Safe)', 'Zone', 'red'),
  '1134': new EventInfo('Entry', 'Zone', 'red'),
  '3134': new EventInfo('Exit', 'Zone', 'green'),
  '1135': new EventInfo('Day', 'Zone', 'red'),
  '3135': new EventInfo('Night', 'Zone', 'green'),
  '1136': new EventInfo('Outdoor', 'Zone', 'red'),
  '1137': new EventInfo('Tamper', 'Zone', 'red'),
  '1138': new EventInfo('Near Alarm', 'Zone', 'red'),
  '1139': new EventInfo('Intrusion Verifier', 'Zone', 'red'),
  '1140': new EventInfo('General Alarm', 'Zone', 'red'),
  '1141': new EventInfo('Polling Loop Open', 'Zone', 'red'),
  '1142': new EventInfo('Polling Loop Short', 'Zone', 'red'),
  '1143': new EventInfo('Expansion Module Failure', 'Zone', 'red'),
  '1144': new EventInfo('Sensor Tamper', 'Zone', 'red'),
  '3144': new EventInfo('Sensor Tamper Restore', 'Zone', 'green'),
  '1145': new EventInfo('Keypad Tamper Open', 'Keypad', 'red'),
  '3145': new EventInfo('Keypad Tamper Closed', 'Keypad', 'green'),
  '1146': new EventInfo('Silent Burglary', 'Zone', 'red'),
  '1147': new EventInfo('Sensor Supervision Failure', 'Zone', 'red'),
  '1150': new EventInfo('24 Hour Non-Burglary', 'Zone', 'red'),
  '1151': new EventInfo('Gas Detected', 'Zone', 'red'),
  '1152': new EventInfo('Refrigeration', 'Zone', 'red'),
  '1153': new EventInfo('Loss Of Heat', 'Zone', 'red'),
  '1154': new EventInfo('Water Leakage', 'Zone', 'red'),
  '1155': new EventInfo('Foil Break', 'Zone', 'red'),
  '1156': new EventInfo('Day Trouble', 'Zone', 'red'),
  '1157': new EventInfo('Low Bottled Gas Level', 'Zone', 'red'),
  '1158': new EventInfo('High Temp', 'Zone', 'red'),
  '1159': new EventInfo('Low Temp', 'Zone', 'red'),
  '1161': new EventInfo('Loss Of Air Flow', 'Zone', 'red'),
  '1162': new EventInfo('Carbon Monoxide Detected', 'Zone', 'red'),
  '1163': new EventInfo('Tank Level', 'Zone', 'red'),
  '1168': new EventInfo('High Humidity', 'Zone', 'red'),
  '1169': new EventInfo('Low Humidity', 'Zone', 'red'),
  '1200': new EventInfo('Fire Supervisory', 'Zone', 'red'),
  '1201': new EventInfo('Low Water Pressure', 'Zone', 'red'),
  '1202': new EventInfo('Low CO2', 'Zone', 'red'),
  '1203': new EventInfo('Gate Valve Sensor', 'Zone', 'red'),
  '1204': new EventInfo('Low Water Level', 'Zone', 'red'),
  '1205': new EventInfo('Pump Activated', 'Zone', 'red'),
  '1206': new EventInfo('Pump Failure', 'Zone', 'red'),
  '1300': new EventInfo('AUX Overload', 'Zone', 'yellow'),
  '3300': new EventInfo('AUX Overload Restore', 'Zone', 'green'),
  '1301': new EventInfo('AC Loss', 'Zone', 'yellow'),
  '3301': new EventInfo('AC Loss Restore', 'Zone', 'green'),
  '1302': new EventInfo('Low System Battery', 'Zone', 'yellow'),
  '3302': new EventInfo('System Battery Restore', 'Zone', 'green'),
  '1303': new EventInfo('RAM Checksum Bad', 'Zone', 'green'),
  '1304': new EventInfo('ROM Checksum Bad', 'Zone', 'green'),
  '1305': new EventInfo('System Reset', 'Zone', 'green'),
  '1306': new EventInfo('Panel Programming Changed', 'Zone', 'green'),
  '1307': new EventInfo('Self-Test Failure', 'Zone', 'green'),
  '1308': new EventInfo('System Shutdown', 'Zone', 'green'),
  '1309': new EventInfo('Battery Test Failure', 'Zone', 'green'),
  '1310': new EventInfo('Ground Fault', 'Zone', 'green'),
  '1311': new EventInfo('Battery Missing/Dead', 'Zone', 'green'),
  '1312': new EventInfo('Power Supply Overcurrent', 'Zone', 'green'),
  '1313': new EventInfo('Engineer Reset', 'User', 'green'),
  '1314': new EventInfo('Primary Power Supply Failure', 'Zone', 'green'),
  '1315': new EventInfo('System Trouble', 'Zone', 'green'),
  '1316': new EventInfo('System Tamper', 'Zone', 'green'),
  '1317': new EventInfo('Control Panel System Tamper', 'Zone', 'green'),
  '1320': new EventInfo('Sounder/Relay', 'Zone', 'green'),
  '1321': new EventInfo('Bell 1 Trouble', 'Zone', 'green'),
  '3321': new EventInfo('Bell 1 Trouble Restore', 'Zone', 'yellow'),
  '1322': new EventInfo('Bell 2 Trouble', 'Zone', 'green'),
  '3322': new EventInfo('Bell 2 Trouble Restore', 'Zone', 'yellow'),
  '1323': new EventInfo('Alarm Relay', 'Zone', 'yellow'),
  '1324': new EventInfo('Trouble Relay', 'Zone', 'yellow'),
  '1325': new EventInfo('Reversing Relay', 'Zone', 'yellow'),
  '1326': new EventInfo('Notification Appliance Ckt. # 3', 'Zone', 'yellow'),
  '1327': new EventInfo('Notification Appliance Ckt. #4', 'Zone', 'yellow'),
  '1330': new EventInfo('System Peripheral Trouble', 'Zone', 'yellow'),
  '1331': new EventInfo('Polling Loop Open', 'Zone', 'yellow'),
  '1332': new EventInfo('Polling Loop Short', 'Zone', 'yellow'),
  '1333': new EventInfo('Expansion Module Failure', 'Zone', 'yellow'),
  '1334': new EventInfo('Repeater Failure', 'Zone', 'yellow'),
  '1335': new EventInfo('Local Printer Out Of Paper', 'Zone', 'yellow'),
  '1336': new EventInfo('Local Printer Failure', 'Zone', 'yellow'),
  '1337': new EventInfo('Exp. Module DC Loss', 'Zone', 'yellow'),
  '1338': new EventInfo('Exp. Module Low Batt.', 'Zone', 'yellow'),
  '1339': new EventInfo('Exp. Module Reset', 'Zone', 'yellow'),
  '1341': new EventInfo('Exp. Module Tamper', 'Zone', 'yellow'),
  '1342': new EventInfo('Exp. Module AC Loss', 'Zone', 'yellow'),
  '1343': new EventInfo('Exp. Module Self-Test Fail', 'Zone', 'yellow'),
  '1344': new EventInfo('RF Receiver Jam Detect', 'Zone', 'yellow'),
  '1345': new EventInfo('AES Encryption Disabled', 'Zone', 'yellow'),
  '3345': new EventInfo('AES Encryption Enabled', 'Zone', 'green'),
  '1350': new EventInfo('Communication Trouble', 'Zone', 'yellow'),
  '1351': new EventInfo('Telco 1 Fault', 'Zone', 'yellow'),
  '1352': new EventInfo('Telco 2 Fault', 'Zone', 'yellow'),
  '1353': new EventInfo('Long Range Radio Xmitter Fault', 'Zone', 'yellow'),
  '1354': new EventInfo('Failure To Communicate Event', 'Zone', 'yellow'),
  '1355': new EventInfo('Loss Of Radio Supervision', 'Zone', 'yellow'),
  '1356': new EventInfo('Loss Of Central Polling', 'Zone', 'yellow'),
  '1357': new EventInfo('Long Range Radio VSWR Problem', 'Zone', 'yellow'),
  '1358': new EventInfo('Periodic Comm Test Fail', 'Zone', 'yellow'),
  '3358': new EventInfo('Periodic Comm Test Restore', 'Zone', 'green'),
  '1370': new EventInfo('Protection Loop', 'Zone', 'yellow'),
  '1371': new EventInfo('Protection Loop Open', 'Zone', 'yellow'),
  '1372': new EventInfo('Protection Loop Short', 'Zone', 'yellow'),
  '1373': new EventInfo('Fire Trouble', 'Zone', 'yellow'),
  '1374': new EventInfo('Exit Error Alarm (Zone)', 'Zone', 'yellow'),
  '1375': new EventInfo('Panic Zone Trouble', 'Zone', 'yellow'),
  '1376': new EventInfo('Hold-Up Zone Trouble', 'Zone', 'yellow'),
  '1377': new EventInfo('Swinger Trouble', 'Zone', 'yellow'),
  '1378': new EventInfo('Cross-zone Trouble', 'Zone', 'yellow'),
  '1380': new EventInfo('Sensor Trouble', 'Zone', 'yellow'),
  '1381': new EventInfo('Loss of RF Supervision', 'Zone', 'yellow'),
  '3381': new EventInfo('RF Supervision Restore', 'Zone', 'green'),
  '1382': new EventInfo('Loss Of Supervision - RPM', 'Zone', 'yellow'),
  '1383': new EventInfo('Sensor Tamper', 'Zone', 'yellow'),
  '1384': new EventInfo('RF Low Battery', 'Zone', 'yellow'),
  '3384': new EventInfo('RF Battery Restore', 'Zone', 'green'),
  '1385': new EventInfo('Smoke Detector Hi Sensitivity', 'Zone', 'yellow'),
  '1386': new EventInfo('Smoke Detector Low Sensitivity', 'Zone', 'yellow'),
  '1387': new EventInfo('Intrusion Detector Hi Sensitivity', 'Zone', 'yellow'),
  '1388':
      new EventInfo('Intrusion Detector Low Sensitivity', 'Zone', 'yellow'),
  '1389': new EventInfo('Sensor Self-Test Failure', 'Zone', 'yellow'),
  '1391': new EventInfo('Sensor Watch Trouble', 'Zone', 'yellow'),
  '1392': new EventInfo('Drift Compensation Error', 'Zone', 'yellow'),
  '1393': new EventInfo('Maintenance Alert', 'Zone', 'yellow'),
  '1394': new EventInfo('CO Detector Needs Replacement', 'Zone', 'yellow'),
  '1400': new EventInfo('Open', 'User', 'yellow'),
  '3400': new EventInfo('Close', 'User', 'green'),
  '1401': new EventInfo('Disarming by user', 'User', 'yellow'),
  '3401': new EventInfo('Arming by user', 'User', 'green'),
  '1402': new EventInfo('Group of zones disarmed', 'User', 'yellow'),
  '3402': new EventInfo('Group of zones armed', 'User', 'green'),
  '1403': new EventInfo('Timed Autodisarming', 'User', 'yellow'),
  '1404': new EventInfo('Late Disarming', 'User', 'yellow'),
  '3403': new EventInfo('Timed Autoarming', 'User', 'green'),
  '3404': new EventInfo('Inactivity Autoarming', 'User', 'green'),
  '1405': new EventInfo('CANCEL Autoarming', 'User', 'yellow'),
  '1406': new EventInfo('Cancel', 'User', 'yellow'),
  '1407': new EventInfo('Remote Disarm', 'User', 'yellow'),
  '1408': new EventInfo('Quick arming', 'User', 'green'),
  '3407': new EventInfo('Remote Arm', 'User', 'green'),
  '3408': new EventInfo('Quick STAY Arm', 'User', 'green'),
  '1409': new EventInfo('Keyswitch Disarming', 'User', 'yellow'),
  '3409': new EventInfo('Keyswitch Arming', 'User', 'green'),
  '3441': new EventInfo('Armed STAY', 'User', 'green'),
  '3442': new EventInfo('Keyswitch Armed Stay', 'User', 'green'),
  '1443':
      new EventInfo('Armed with System Trouble Override', 'User', 'yellow'),
  '1444': new EventInfo('Armed Night Stay', 'User', 'yellow'),
  '1450': new EventInfo('Exception Open', 'User', 'yellow'),
  '3450': new EventInfo('Exception Close', 'User', 'green'),
  '1451': new EventInfo('Early Open', 'User', 'yellow'),
  '3451': new EventInfo('Early Close', 'User', 'green'),
  '1452': new EventInfo('Late Open', 'User', 'yellow'),
  '3452': new EventInfo('Late Close', 'User', 'green'),
  '1453': new EventInfo('Failed To Open', 'User', 'yellow'),
  '1454': new EventInfo('Failed To Close', 'User', 'yellow'),
  '1455': new EventInfo('Autoarm Failed', 'User', 'yellow'),
  '3456': new EventInfo('Partial Arm', 'User', 'green'),
  '1457': new EventInfo('Exit Error (User)', 'User', 'yellow'),
  '1458': new EventInfo('User On Premises', 'User', 'yellow'),
  '1459': new EventInfo('Recent Close', 'User', 'yellow'),
  '1461': new EventInfo('Wrong Code Entry', 'Keypad', 'yellow'),
  '1462': new EventInfo('Legal Code Entry', 'Keypad', 'yellow'),
  '1463': new EventInfo('Re-Arm After Alarm', 'User', 'yellow'),
  '1464': new EventInfo('auto-Arm Time Extended', 'User', 'yellow'),
  '1465': new EventInfo('Panic Alarm Reset', 'Zone', 'yellow'),
  '1466': new EventInfo('Service On Premises', 'User', 'yellow'),
  '3466': new EventInfo('Service Off Premises', 'User', 'green'),
  '1411': new EventInfo('Callback Request Made', 'User', 'grey'),
  '1412': new EventInfo('PC Connected', 'User', 'grey'),
  '3412': new EventInfo('PC Disconnected', 'User', 'grey'),
  '1413': new EventInfo('Unsuccessful Access', 'User', 'grey'),
  '1414': new EventInfo('System Shutdown Command Received', 'User', 'grey'),
  '1415': new EventInfo('Dialer Shutdown Command Received', 'User', 'grey'),
  '1416': new EventInfo('Successful Upload', 'Zone', 'grey'),
  '1421': new EventInfo('Keypad Lockout', 'Keypad', 'red'),
  '1422': new EventInfo('PGM Activated by User', 'User', 'grey'),
  '3422': new EventInfo('PGM Deactivated by User', 'User', 'grey'),
  '1423': new EventInfo('Guard Round Ambush', 'Zone', 'red'),
  '1424': new EventInfo('Egress Denied', 'User', 'grey'),
  '1425': new EventInfo('Egress Granted', 'User', 'grey'),
  '1426': new EventInfo('Access Door Propped Open', 'Zone', 'grey'),
  '1427': new EventInfo(
      'Access Point Door Status Monitor Trouble', 'Zone', 'grey'),
  '1428':
      new EventInfo('Access Point Request To Exit Trouble', 'Zone', 'grey'),
  '1429': new EventInfo('Guard Round Starts', 'User', 'grey'),
  '1430': new EventInfo('Guard Round Finish', 'User', 'grey'),
  '1431': new EventInfo('Access Threat Level Change', 'User', 'grey'),
  '1432': new EventInfo('Access Relay/Trigger Fail', 'Zone', 'grey'),
  '1433': new EventInfo('Access RTE Shunt', 'Zone', 'grey'),
  '1434': new EventInfo('Access DSM Shunt', 'Zone', 'grey'),
  '1435': new EventInfo('Second Person Access', 'User', 'grey'),
  '1436': new EventInfo('Irregular Access', 'User', 'grey'),
  '1501': new EventInfo('Access Reader Disable', 'Zone', 'grey'),
  '1520': new EventInfo('Sounder/Relay Disable', 'Zone', 'grey'),
  '1521': new EventInfo('Bell 1 Disable', 'Zone', 'grey'),
  '1522': new EventInfo('Bell 2 Disable', 'Zone', 'grey'),
  '1523': new EventInfo('Alarm Relay Disable', 'Zone', 'grey'),
  '1524': new EventInfo('Trouble Relay Disable', 'Zone', 'grey'),
  '1525': new EventInfo('Reversing Relay Disable', 'Zone', 'grey'),
  '1526':
      new EventInfo('Notification Appliance Ckt. # 3 Disable', 'Zone', 'grey'),
  '1527':
      new EventInfo('Notification Appliance Ckt. # 4 Disable', 'Zone', 'grey'),
  '1531': new EventInfo('Module Added', 'Zone', 'grey'),
  '1532': new EventInfo('Module Removed', 'Zone', 'grey'),
  '1551': new EventInfo('Dialer Disabled', 'Zone', 'grey'),
  '1552': new EventInfo('Radio Transmitter Disabled', 'Zone', 'grey'),
  '1553': new EventInfo('Remote Upload/Download Disabled', 'Zone', 'grey'),
  '1554': new EventInfo('Fiber Converter Fault', 'Zone', 'grey'),
  '1555': new EventInfo('Fiber Network Fault', 'Zone', 'grey'),
  '1570': new EventInfo('Zone Bypass', 'Zone', 'yellow'),
  '1571': new EventInfo('Fire Bypass', 'Zone', 'yellow'),
  '1572': new EventInfo('24 Hour Zone Bypass', 'Zone', 'yellow'),
  '1573': new EventInfo('Burg. Bypass', 'Zone', 'yellow'),
  '1574': new EventInfo('Group Bypass', 'User', 'yellow'),
  '1575': new EventInfo('Swinger Bypass', 'Zone', 'yellow'),
  '1576': new EventInfo('Access Zone Shunt', 'Zone', 'yellow'),
  '1577': new EventInfo('Access Point Bypass', 'Zone', 'yellow'),
  '1578': new EventInfo('Vault Bypass', 'Zone', 'yellow'),
  '1579': new EventInfo('Vent Zone Bypass', 'Zone', 'yellow'),
  '1601': new EventInfo('Manual Trigger Test Report', 'Zone', 'grey'),
  '1602': new EventInfo('Periodic Test Report', 'Zone', 'grey'),
  '1603': new EventInfo('Periodic RF Transmission', 'Zone', 'grey'),
  '1604': new EventInfo('Fire Test', 'User', 'grey'),
  '1605': new EventInfo('Status Report To Follow', 'Zone', 'grey'),
  '1606': new EventInfo('Listen-In To Follow', 'Zone', 'grey'),
  '1607': new EventInfo('Walk Test Mode', 'User', 'grey'),
  '1608': new EventInfo(
      'Periodic Test - System Trouble Present', 'Zone', 'yellow'),
  '1609': new EventInfo('Video Xmitter Active', 'Zone', 'grey'),
  '1611': new EventInfo('Round OK', 'Zone', 'green'),
  '1612': new EventInfo('Round Failed', 'Zone', 'yellow'),
  '1613': new EventInfo('Intrusion Zone Walk Tested', 'Zone', 'grey'),
  '1614': new EventInfo('Fire Zone Walk Tested', 'Zone', 'grey'),
  '1615': new EventInfo('Panic Zone Walk Tested', 'Zone', 'grey'),
  '1616': new EventInfo('Service Request', 'Zone', 'grey'),
  '1621': new EventInfo('Event Log Reset', 'Zone', 'grey'),
  '1622': new EventInfo('Event Log 50% Full', 'Zone', 'grey'),
  '1623': new EventInfo('Event Log 90% Full', 'Zone', 'grey'),
  '1624': new EventInfo('Event Log Overflow', 'Zone', 'grey'),
  '1625': new EventInfo('Time/Date Reset', 'User', 'grey'),
  '1626': new EventInfo('Time/Date Inaccurate', 'Zone', 'yellow'),
  '3626': new EventInfo('Time/Date Restore', 'Zone', 'green'),
  '1627': new EventInfo('Program Mode Entry', 'Zone', 'yellow'),
  '1628': new EventInfo('Program Mode Exit', 'Zone', 'green'),
  '1629': new EventInfo('32 Hour Event Log Marker', 'Zone', 'grey'),
  '1630': new EventInfo('Schedule Change', 'Zone', 'grey'),
  '1631': new EventInfo('Exception Schedule Change', 'Zone', 'grey'),
  '1632': new EventInfo('Access Schedule Change', 'Zone', 'grey'),
  '1641': new EventInfo('Senior Watch Trouble', 'Zone', 'grey'),
  '1642': new EventInfo('Latch-Key Supervision', 'User', 'grey'),
  '1643': new EventInfo('Restricted Door Opened', 'Zone', 'grey'),
  '1645': new EventInfo('Help Arrived', 'Zone', 'grey'),
  '1646': new EventInfo('Additional Help Needed', 'Zone', 'grey'),
  '1647': new EventInfo('Additional Help Cancel', 'Zone', 'grey'),
  '1651': new EventInfo('Reserved For Ademco Use', 'Zone', 'grey'),
  '1652': new EventInfo('Reserved For Ademco Use', 'User', 'grey'),
  '1653': new EventInfo('Reserved For Ademco Use', 'User', 'grey'),
  '1654': new EventInfo('System Inactivity', 'Zone', 'grey'),
  '1655': new EventInfo('User Code X modified by Installer', 'User', 'grey'),
  '1703': new EventInfo('Auxiliary #3', 'Zone', 'grey'),
  '1704': new EventInfo('Installer Test', 'Zone', 'grey'),
  '1760': new EventInfo('LINE is Free', null, 'grey'),
  '3760': new EventInfo('LINE is Restored', null, 'grey'),
  '1761': new EventInfo('INPUT 1 is ON', null, 'grey'),
  '3761': new EventInfo('INPUT 1 is OFF', null, 'grey'),
  '1762': new EventInfo('INPUT 2 is ON', null, 'grey'),
  '3762': new EventInfo('INPUT 2 is OFF', null, 'grey'),
  '1763': new EventInfo('PGM 1 is ON', null, 'grey'),
  '3763': new EventInfo('PGM 1 is OFF', null, 'grey'),
  '1764': new EventInfo('PGM 2 is ON', null, 'grey'),
  '3764': new EventInfo('PGM 2 is OFF', null, 'grey'),
  '1765': new EventInfo('PGM 3 is ON', null, 'grey'),
  '3765': new EventInfo('PGM 3 is OFF', null, 'grey'),
  '1766': new EventInfo('PGM 4 is ON', null, 'grey'),
  '3766': new EventInfo('PGM 4 is OFF', null, 'grey'),
  '1767': new EventInfo('INPUT 3 is ON', null, 'grey'),
  '3767': new EventInfo('INPUT 3 is OFF', null, 'grey'),
  '1770': new EventInfo('GPRS Initialization Failure', null, 'yellow'),
  '3770': new EventInfo('GPRS Initialization OK', null, 'green'),
  '1771': new EventInfo('Ethernet Failure', null, 'yellow'),
  '3771': new EventInfo('Ethernet is UP', null, 'green'),
  '1772': new EventInfo('GPRS Failure', null, 'yellow'),
  '3772': new EventInfo('GPRS is UP', null, 'green'),
  '1774': new EventInfo('Low Cellular Signal', null, 'yellow'),
  '3774': new EventInfo('Normal Cellular Signal', null, 'green'),
  '1775': new EventInfo('Cellular Module Removed', null, 'yellow'),
  '3775': new EventInfo('Cellular Module Inserted', null, 'green'),
  '1776': new EventInfo('SIM Card Removed', null, 'yellow'),
  '3776': new EventInfo('SIM Card Inserted', null, 'green'),
  '1777': new EventInfo('Input Bypassed', null, 'yellow'),
  '3777': new EventInfo('Input Restored', null, 'green'),
  '1796': new EventInfo(
      'Unable to output signal (Derived Channel)', 'Zone', 'grey'),
  '1798':
      new EventInfo('STU Controller down (Derived Channel)', 'Zone', 'grey'),
  '1910': new EventInfo('auto-close with Bypass', 'Zone', 'grey'),
  '1911': new EventInfo('Bypass Closing', 'Zone', 'grey'),
  '1912': new EventInfo('Fire Alarm Silence', 'Zone', 'grey'),
  '1913': new EventInfo('Supervisory Point test Start/End', 'User', 'grey'),
  '1914': new EventInfo('Hold-up test Start/End', 'User', 'grey'),
  '1915': new EventInfo('Burg. Test Print Start/End', 'User', 'grey'),
  '1916': new EventInfo('Supervisory Test Print Start/End', 'User', 'grey'),
  '1917': new EventInfo('Burg. Diagnostics Start/End', 'Zone', 'grey'),
  '1918': new EventInfo('Fire Diagnostics Start/End', 'Zone', 'grey'),
  '1919': new EventInfo('Untyped diagnostics', 'Zone', 'grey'),
  '1920': new EventInfo(
      'Trouble Closing (Closed with burg. during exit)', 'User', 'grey'),
  '1921': new EventInfo('Access Denied Code Unknown', 'User', 'grey'),
  '1922': new EventInfo('Supervisory Point Alarm', 'Zone', 'grey'),
  '1923': new EventInfo('Supervisory Point Bypass', 'Zone', 'grey'),
  '1924': new EventInfo('Supervisory Point Trouble', 'Zone', 'grey'),
  '1925': new EventInfo('Hold-up Point Bypass', 'Zone', 'grey'),
  '1926': new EventInfo('AC Failure for 4 hours', 'Zone', 'grey'),
  '1927': new EventInfo('Output Trouble', 'Zone', 'grey'),
  '1928': new EventInfo('User code for event', 'User', 'grey'),
  '1929': new EventInfo('Log-off', 'User', 'grey'),
  '1954': new EventInfo('CS Connection Failure', 'Zone', 'grey'),
  '1961':
      new EventInfo('Rcvr Database Connection Fail/Restore', 'Zone', 'grey'),
  '1962': new EventInfo('License Expiration Notification', 'Zone', 'grey'),
  '3100': new EventInfo('Medical Alarm Restore', 'Zone', 'green'),
  '3101': new EventInfo('Personal Emergency Restore', 'Zone', 'green'),
  '3102': new EventInfo('Communication Error Restore', 'Zone', 'green'),
  '3110': new EventInfo('Fire Restore', 'Zone', 'green'),
  '3111': new EventInfo('Smoke Restore', 'Zone', 'green'),
  '3112': new EventInfo('Comubstion Restore', 'Zone', 'green'),
  '3113': new EventInfo('Water Flow Restore', 'Zone', 'green'),
  '3114': new EventInfo('Heat Restore', 'Zone', 'green'),
  '3115': new EventInfo('Pull Station Restore', 'Zone', 'green'),
  '3116': new EventInfo('Duct Restore Restore', 'Zone', 'green'),
  '3117': new EventInfo('Flame Restore', 'Zone', 'green'),
  '3118': new EventInfo('Near Alarm Restore', 'Zone', 'green'),
  '3120': new EventInfo('Panic Restore', 'Zone', 'green'),
  '3121': new EventInfo('Ambush Restore', 'User', 'green'),
  '3122': new EventInfo('Silent Restore', 'Zone', 'green'),
  '3123': new EventInfo('Audible Restore', 'Zone', 'green'),
  '3124': new EventInfo('Duress - Access Granted Restore', 'Zone', 'green'),
  '3125': new EventInfo('Duress - Egress Granted Restore', 'Zone', 'green'),
  '3131': new EventInfo('Perimeter Restore', 'Zone', 'green'),
  '3132': new EventInfo('Interior Restore', 'Zone', 'green'),
  '3133': new EventInfo('24 Hour (Safe) Restore', 'Zone', 'green'),
  '3136': new EventInfo('Outdoor Restore', 'Zone', 'green'),
  '3137': new EventInfo('Tamper Restore', 'Zone', 'green'),
  '3138': new EventInfo('Near Alarm Restore', 'Zone', 'green'),
  '3139': new EventInfo('Intrusion Verifier Restore', 'Zone', 'green'),
  '3140': new EventInfo('General Alarm Restore', 'Zone', 'green'),
  '3141': new EventInfo('Polling Loop Open Restore', 'Zone', 'green'),
  '3142': new EventInfo('Polling Loop Short Restore', 'Zone', 'green'),
  '3143': new EventInfo('Expansion Module Failure Restore', 'Zone', 'green'),
  '3146': new EventInfo('Silent Burglary Restore', 'Zone', 'green'),
  '3147': new EventInfo('Sensor Supervision Failure Restore', 'Zone', 'green'),
  '3150': new EventInfo('24 Hour Non-Burglary Restore', 'Zone', 'green'),
  '3151': new EventInfo('Gas Detected Restore', 'Zone', 'green'),
  '3152': new EventInfo('Refrigeration Restore', 'Zone', 'green'),
  '3153': new EventInfo('Loss Of Heat Restore', 'Zone', 'green'),
  '3154': new EventInfo('Water Leakage Restore', 'Zone', 'green'),
  '3155': new EventInfo('Foil Break Restore', 'Zone', 'green'),
  '3156': new EventInfo('Day Trouble Restore', 'Zone', 'green'),
  '3157': new EventInfo('Low Bottled Gas Level Restore', 'Zone', 'green'),
  '3158': new EventInfo('High Temp Restore', 'Zone', 'green'),
  '3159': new EventInfo('Low Temp Restore', 'Zone', 'green'),
  '3161': new EventInfo('Loss Of Air Flow Restore', 'Zone', 'green'),
  '3162': new EventInfo('Carbon Monoxide Detected Restore', 'Zone', 'green'),
  '3163': new EventInfo('Tank Level Restore', 'Zone', 'green'),
  '3200': new EventInfo('Fire Supervisory Restore', 'Zone', 'green'),
  '3201': new EventInfo('Low Water Pressure Restore', 'Zone', 'green'),
  '3202': new EventInfo('Low CO2 Restore', 'Zone', 'green'),
  '3203': new EventInfo('Gate Valve Sensor Restore', 'Zone', 'green'),
  '3204': new EventInfo('Low Water Level Restore', 'Zone', 'green'),
  '3205': new EventInfo('Pump Activated Restore', 'Zone', 'green'),
  '3206': new EventInfo('Pump Failure Restore', 'Zone', 'green'),
  '3303': new EventInfo('RAM Checksum Restore', 'Zone', 'green'),
  '3304': new EventInfo('ROM Checksum Restore', 'Zone', 'green'),
  '3305': new EventInfo('System Reset Restore', 'Zone', 'green'),
  '3306': new EventInfo('Panel Programming Changed Restore', 'Zone', 'green'),
  '3307': new EventInfo('Self-Test Failure Restore', 'Zone', 'green'),
  '3308': new EventInfo('System Shutdown Restore', 'Zone', 'green'),
  '3309': new EventInfo('Battery Test Failure Restore', 'Zone', 'green'),
  '3310': new EventInfo('Ground Fault Restore', 'Zone', 'green'),
  '3311': new EventInfo('Battery Missing/Dead Restore', 'Zone', 'green'),
  '3312': new EventInfo('Power Supply Overcurrent Restore', 'Zone', 'green'),
  '3313': new EventInfo('Engineer Reset Restore', 'User', 'green'),
  '3320': new EventInfo('Sounder/Relay Restore', 'Zone', 'green'),
  '3323': new EventInfo('Alarm Relay Restore', 'Zone', 'green'),
  '3324': new EventInfo('Trouble Relay Restore', 'Zone', 'green'),
  '3325': new EventInfo('Reversing Relay Restore', 'Zone', 'green'),
  '3326': new EventInfo(
      'Notification Appliance Ckt. # 3 Restore', 'Zone', 'green'),
  '3327': new EventInfo(
      'Notification Appliance Ckt. # 4 Restore', 'Zone', 'green'),
  '3330': new EventInfo('System Peripheral Trouble  Restore', 'Zone', 'green'),
  '3331': new EventInfo('Polling Loop Open Restore', 'Zone', 'green'),
  '3332': new EventInfo('Polling Loop Short Restore', 'Zone', 'green'),
  '3333': new EventInfo('Expansion Module Failure Restore', 'Zone', 'green'),
  '3334': new EventInfo('Repeater Failure Restore', 'Zone', 'green'),
  '3335': new EventInfo('Local Printer Out Of Paper Restore', 'Zone', 'green'),
  '3336': new EventInfo('Local Printer Failure Restore', 'Zone', 'green'),
  '3337': new EventInfo('Exp. Module DC Loss Restore', 'Zone', 'green'),
  '3338': new EventInfo('Exp. Module Low Batt. Restore', 'Zone', 'green'),
  '3339': new EventInfo('Exp. Module Reset Restore', 'Zone', 'green'),
  '3341': new EventInfo('Exp. Module Tamper Restore', 'Zone', 'green'),
  '3342': new EventInfo('Exp. Module AC Loss Restore', 'Zone', 'green'),
  '3343': new EventInfo('Exp. Module Self-Test Fail Restore', 'Zone', 'green'),
  '3344': new EventInfo('RF Receiver Jam Detect Restore', 'Zone', 'green'),
  '3350': new EventInfo('Communication Trouble Restore', 'Zone', 'green'),
  '3351': new EventInfo('Telco 1 Fault Restore', 'Zone', 'green'),
  '3352': new EventInfo('Telco 2 Fault Restore', 'Zone', 'green'),
  '3353':
      new EventInfo('Long Range Radio Xmitter Fault Restore', 'Zone', 'green'),
  '3354':
      new EventInfo('Failure To Communicate Event Restore', 'Zone', 'green'),
  '3355': new EventInfo('Loss Of Radio Supervision Restore', 'Zone', 'green'),
  '3356': new EventInfo('Loss Of Central Polling Restore', 'Zone', 'green'),
  '3357':
      new EventInfo('Long Range Radio VSWR Problem Restore', 'Zone', 'green'),
  '3370': new EventInfo('Protection Loop Restore', 'Zone', 'green'),
  '3371': new EventInfo('Protection Loop Open Restore', 'Zone', 'green'),
  '3372': new EventInfo('Protection Loop Short Restore', 'Zone', 'green'),
  '3373': new EventInfo('Fire Trouble Restore', 'Zone', 'green'),
  '3374': new EventInfo('Exit Error Alarm (Zone) Restore', 'Zone', 'green'),
  '3375': new EventInfo('Panic Zone Trouble Restore', 'Zone', 'green'),
  '3376': new EventInfo('Hold-Up Zone Trouble Restore', 'Zone', 'green'),
  '3377': new EventInfo('Swinger Trouble Restore', 'Zone', 'green'),
  '3378': new EventInfo('Cross-zone Trouble Restore', 'Zone', 'green'),
  '3380': new EventInfo('Sensor Trouble Restore', 'Zone', 'green'),
  '3382': new EventInfo('Loss Of Supervision - RPM Restore', 'Zone', 'green'),
  '3383': new EventInfo('Sensor Tamper Restore', 'Zone', 'green'),
  '3385':
      new EventInfo('Smoke Detector Hi Sensitivity Restore', 'Zone', 'green'),
  '3386':
      new EventInfo('Smoke Detector Low Sensitivity Restore', 'Zone', 'green'),
  '3387': new EventInfo(
      'Intrusion Detector Hi Sensitivity Restor', 'Zone', 'green'),
  '3388': new EventInfo(
      'Intrusion Detector Low Sensitivity Restore', 'Zone', 'green'),
  '3389': new EventInfo('Sensor Self-Test Failure Restore', 'Zone', 'green'),
  '3391': new EventInfo('Sensor Watch Trouble Restore', 'Zone', 'green'),
  '3392': new EventInfo('Drift Compensation Error Restore', 'Zone', 'green'),
  '3393': new EventInfo('Maintenance Alert Restore', 'Zone', 'green'),
  '3426': new EventInfo('Access Door Propped Open Restore', 'Zone', 'green'),
  '3427': new EventInfo(
      'Access Point Door Status Monitor Trouble Restore', 'Zone', 'green'),
  '3428': new EventInfo(
      'Access Point Request To Exit Trouble Restore', 'Zone', 'green'),
  '3432': new EventInfo('Access Relay/Trigger Fail Restore', 'Zone', 'green'),
  '3433': new EventInfo('Access RTE Shunt Restore', 'Zone', 'green'),
  '3434': new EventInfo('Access DSM Shunt Restore', 'Zone', 'green'),
  '3501': new EventInfo('Access Reader Enable', 'Zone', 'green'),
  '3520': new EventInfo('Sounder/Relay Enable', 'Zone', 'green'),
  '3521': new EventInfo('Bell 1 Enable', 'Zone', 'green'),
  '3522': new EventInfo('Bell 2 Enable', 'Zone', 'green'),
  '3523': new EventInfo('Alarm Relay Enable', 'Zone', 'green'),
  '3524': new EventInfo('Trouble Relay Enable', 'Zone', 'green'),
  '3525': new EventInfo('Reversing Relay Enable', 'Zone', 'green'),
  '3551': new EventInfo('Dialer Enabled', 'Zone', 'green'),
  '3552': new EventInfo('Radio Transmitter Enabled', 'Zone', 'green'),
  '3553': new EventInfo('Remote Upload/Download Enabled', 'Zone', 'green'),
  '3570': new EventInfo('Zone Bypass Cancel', 'Zone', 'yellow'),
  '3571': new EventInfo('Fire Bypass Cancel', 'Zone', 'yellow'),
  '3572': new EventInfo('24 Hour Zone Bypass Cancel', 'Zone', 'yellow'),
  '3573': new EventInfo('Burg. Bypass Cancel', 'Zone', 'yellow'),
  '3574': new EventInfo('Group Bypass Cancel', 'User', 'yellow'),
  '3575': new EventInfo('Swinger Bypass Cancel', 'Zone', 'yellow'),
  '3576': new EventInfo('Access Zone Shunt Open', 'Zone', 'yellow'),
  '3577': new EventInfo('Access Point Bypass Cancel', 'Zone', 'yellow'),
};