name: Deploy to Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up SSH and deploy to server
      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Passphrase for the SSH key
          command_timeout: 20m  # Increased timeout
          script: |
            # Add GitHub's SSH key to known hosts
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Start ssh-agent and add the SSH key with the passphrase
            eval $(ssh-agent -s)  # Start the ssh-agent in the background
            
            # Save the SSH private key to a file
            echo "$SSH_PRIVATE_KEY" > /tmp/id_ed25519
            chmod 600 /tmp/id_ed25519

            # Add the private key to ssh-agent
            ssh-add /tmp/id_ed25519 || exit 1

            # Change to the directory where the repo should be located
            cd /home || exit 1

            # Check if the repository already exists
            if [ ! -d notifications-server ]; then
              echo "Repository not found. Cloning the repository using SSH..."
              git clone git@github.com:EuEric/push-notification-server-node.git notifications-server || exit 1
            else
              echo "Repository found. Pulling the latest changes..."
              cd notifications-server || exit 1
              git pull origin main || exit 1
            fi

            # Pull latest Docker images and restart containers
            cd notifications-server || exit 1
            docker-compose pull || exit 1
            docker-compose up -d || exit 1
