name: Deploy to Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key stored in secrets
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Use the passphrase if available
          command_timeout: 20m
          script: |
            # Start the ssh-agent in the background
            eval $(ssh-agent -s)

            # Load the existing private key into the SSH agent with passphrase
            echo "$${{ secrets.SSH_PASSPHRASE }}" | ssh-add /root/.ssh/id_ed25519

            # Check if the repository already exists
            cd /root || exit 1
            if [ ! -d notifications-server ]; then
              echo "Repository not found. Cloning the repository using SSH..."
              git clone git@github.com:EuEric/push-notification-server-node.git || exit 1
            else
              echo "Repository found. Pulling the latest changes..."
              cd notifications-server || exit 1
              git pull origin main || exit 1
            fi

            # Pull latest Docker images and restart containers
            docker-compose pull || exit 1
            docker-compose up -d || exit 1