name: Deploy to Server

on:
  push:
    branches: 
      - main
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      #Set up SSH connection
      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          command_timeout: 20m
          script: | 

            # Start ssh-agent and add the SSH key with the passphrase
            eval $(ssh-agent -s)  # Start the ssh-agent in the background
            echo "$PRIVATE_KEY_GIT_SSH" | ssh-add - <<< "$SSH_PASSPHRASE"  # Add the private key and provide passphrase

            #Change to home directory before cloning, if needed
            cd /home || exit 1
            # Check if .git directory exists
            if [ ! -d .git ]; then
              echo "Repository not found. Cloning the repository using SSH..."
              # Use sshpass to provide passphrase for the key
              export SSHPASS="${{ secrets.SSH_PASSPHRASE }}"
              sshpass -e git clone -v git@github.com:EuEric/push-notification-server-node.git || exit 1
            else
              echo "Repository found. Pulling the latest changes..."
              #Enter project root
              cd ${{ secrets.PROJECT_FOLDER }} || exit 1
              git pull origin main || exit 1
            fi

            #Enter project root
            cd ${{ secrets.PROJECT_FOLDER }} || exit 1
            docker-compose pull || exit 1
            docker-compose up -d || exit 1