name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          command_timeout: 20m
          script: |
            # Start the ssh-agent in the background
            eval $(ssh-agent -s)

            # Add the private key to the agent without the passphrase
            ssh-add /root/.ssh/id_ed25519

            # Check if the repository already exists
            cd /root || exit 1
            if [ ! -d push-notification-server-node ]; then
              echo "Repository not found. Cloning the repository using SSH..."
              git clone -v git@github.com:EuEric/push-notification-server-node.git || exit 1
              cd push-notification-server-node || exit 1
            else
              echo "Repository found. Pulling the latest changes..."
              cd push-notification-server-node || exit 1
              git pull origin master || exit 1
            fi

            # Pull latest Docker images and restart containers
            docker-compose pull || exit 1
            docker-compose up -d || exit 1